@startuml c4_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Диаграмма контекста ИС "Брадобрей-пати" (Уровень L1)

Person(client, "Клиент")
Person(staff, "Персонал", "Мастера, менеджеры, бухгалтеры, администраторы")

System(bb_system, "Брадобрей-пати", "Веб-приложение для управления сетью барбершопов, записями и аналитикой")

System_Ext(payment_gate, "Обработчик отчетов", "Генерация отчётов в PDF формате")
System_Ext(map_service, "Гео-сервис")

Rel(client, bb_system, "Просматривает услуги, записывается, оплачивает")
Rel(staff, bb_system, "Управляет записями, штатом и смотрит отчеты")
Rel(bb_system, payment_gate, "Запрашивает создание отчетов")
Rel(bb_system, map_service, "Запрашивает координаты и карты")
@enduml